name: PHP Lint

on:
  push:
    branches: [ default_branch_name ]
  pull_request:
    branches: [ default_branch_name ]

jobs:
  phplint:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: PHP Lint
      uses: michaelw90/PHP-Lint@2.1.0
